// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzdCk4gpacS1305h2VualrAnXUQ_SDyto',
    appId: '1:796397871247:web:8bbf2efaaface7849910fa',
    messagingSenderId: '796397871247',
    projectId: 'swapi-app-4f7b4',
    authDomain: 'swapi-app-4f7b4.firebaseapp.com',
    storageBucket: 'swapi-app-4f7b4.firebasestorage.app',
    measurementId: 'G-EVGN6XETYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBobgw2W9SS-zV3xOyuc9Xl2ypePJchqbo',
    appId: '1:796397871247:android:917ccce51a4b4cfd9910fa',
    messagingSenderId: '796397871247',
    projectId: 'swapi-app-4f7b4',
    storageBucket: 'swapi-app-4f7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSaEJ3RJWtiJF9vbuivVovh3ZV_S6qbm4',
    appId: '1:796397871247:ios:b69ba4d5f2704d709910fa',
    messagingSenderId: '796397871247',
    projectId: 'swapi-app-4f7b4',
    storageBucket: 'swapi-app-4f7b4.firebasestorage.app',
    iosClientId:
        '796397871247-afnkmck5hviu0otj74dgnmci1k4bcsuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.swapiApp',
  );
}
